version: '3'

x-service:
  &base-service
  restart: always
  env_file:
    - .env


services:

  db-blog:
    <<: *base-service
    image: postgres:14.2
    ports:
      - '4314:5432'
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
